FROM nginx
COPY tgc/staticfiles /usr/share/nginx/html
COPY uwsgi_params /usr/share/nginx
RUN rm /etc/nginx/conf.d/default.conf
ADD nginx-app.conf /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]
