tgc:
  image: imauld/tgc
  links:
    - redis
  ports:
    - "8000:8000"
nginx:
  image: imauld/tgcnginx
  links:
    - tgc:tgc
  ports:
    - "80:80"
    - "8080:8080"
redis:
  image: redis:latest
  ports:
    - "6379:6379"
